Repository TomographicImaging/CCPi-Regularisation-Toolkit, pull requests merged in 2024-03, with the labels that each got.

#183 Remove the Cython layer and use ctypes
  .gitignore
  CMakeLists.txt
  Installation.md
  demos/demo_cpu_regularisers3D.py
  demos/demo_cpu_vs_gpu_regularisers.py
  demos/demo_gpu_regularisers.py
  demos/demo_gpu_regularisers3D.py
  pyproject.toml
  recipe/meta.yaml
  src/Core/CMakeLists.txt
  src/Python/CMakeLists.txt
  src/Python/ccpi/filters/TV.py
  src/Python/ccpi/filters/diffusion.py
  src/Python/ccpi/filters/regularisers.py
  src/Python/ccpi/filters/utils.py
  src/Python/pyproject.toml
  src/Python/setup-regularisers.py.in
  test/test_CPU_regularisers.py
  test/test_run_test.py
Labels: bug, enhancement, in progress

#189 fix conda build
  CMakeLists.txt
  Installation.md
  build/run.sh
  recipe/bld.bat
  recipe/build.sh
  recipe/meta.yaml
  src/Core/CMakeLists.txt
  src/Python/CMakeLists.txt
  src/Python/ccpi/filters/TV.py
  src/Python/ccpi/filters/utils.py
  src/Python/pyproject.toml
Labels: bug

#193 CI: add GHA workflow
  .github/workflows/build.yml
  recipe/meta.yaml
  src/Python/pyproject.toml
Labels: bug, enhancement

#196 CI: add self-hosted CUDA runners
  .github/workflows/build.yml
Labels: enhancement
